export { CreateSectionPage } from './CreateSectionPage'
export { MainPage } from './MainPage'
export { CurrentNews } from './CurrentNews'
export { CreateNewsPage } from './CreateNewsPage'
export { ChangeNewsPage } from './ChangeNewsPage/ChangeNewsPage'
